/**
 * OPTIMAT Frontend API Module
 *
 * This module provides a unified API interface using Supabase Edge Functions.
 * All API calls are routed through Supabase Edge Functions with REST-style routing.
 */

import {
  isSupabaseConfigured,
  fetchEdgeFunction,
  getEdgeFunctionUrl,
  getAuthHeaders,
  getSupabaseRestUrl,
  getRestHeaders,
  getApiBackend,
} from './supabase';

// =============================================================================
// Types
// =============================================================================

export interface GeocodeResult {
  success: boolean;
  lat?: number;
  lng?: number;
  latitude?: number;
  longitude?: number;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  formatted_address?: string;
  place_id?: string;
  message?: string;
  error?: string;
}

export interface Provider {
  id?: string;
  provider_id?: string | number;
  provider_name: string;
  provider_type: string;
  provider_org?: string;
  service_zone?: string | object;
  service_area_cities?: string[];
  service_area_source?: string;
  service_area_notes?: string;
  provider_software?: string | null;
  has_service_zone?: boolean;
  service_hours?: string | object;
  eligibility_reqs?: string | string[] | object | null;
  booking?: string | object;
  website?: string;
  latitude?: number;
  longitude?: number;
  routing_type?: string;
  planning_type?: string;
  schedule_type?: string | object;
  fare?: string | object;
  round_trip_booking?: boolean;
  investigated?: boolean;
  is_operating?: boolean;
  _zone_color?: string;
}

export type ProviderUpdate = Partial<Omit<Provider, 'id' | 'provider_id' | 'created_at' | 'updated_at' | '_zone_color'>>;

function parseJsonIfString(value: unknown): unknown {
  if (typeof value !== 'string') return value;
  const trimmed = value.trim();
  if (!trimmed) return value;
  const first = trimmed[0];
  if (first !== '{' && first !== '[') return value;
  try {
    return JSON.parse(trimmed);
  } catch {
    return value;
  }
}

function normalizeProviderForUi(provider: Provider): Provider {
  return {
    ...provider,
    schedule_type: parseJsonIfString(provider.schedule_type) as Provider['schedule_type'],
    eligibility_reqs: parseJsonIfString(provider.eligibility_reqs) as Provider['eligibility_reqs'],
    booking: parseJsonIfString(provider.booking) as Provider['booking'],
    fare: parseJsonIfString(provider.fare) as Provider['fare'],
    service_hours: parseJsonIfString(provider.service_hours) as Provider['service_hours'],
    service_zone: parseJsonIfString(provider.service_zone) as Provider['service_zone'],
  };
}

export interface ProviderFilterRequest {
  source_address: string;
  destination_address: string;
  schedule_type?: string;
  provider_type?: string;
}

export interface ProviderFilterResponse {
  data: Provider[];
  source_address?: string;
  destination_address?: string;
  source_coords?: { lat: number; lng: number };
  destination_coords?: { lat: number; lng: number };
  origin?: { lat: number; lon: number } | null;
  destination?: { lat: number; lon: number } | null;
  message?: string;
  error?: string;
  details?: unknown;
  public_transit?: {
    journey_description?: string;
    routes?: unknown[];
  };
}

export interface ConversationMessage {
  id?: string;
  role: 'human' | 'ai' | 'assistant' | 'user' | 'system';
  content: string;
  created_at?: string;
  conversation_id?: string;
  attachments?: unknown[] | null;
}

export interface Conversation {
  id: string;
  title?: string;
  created_at?: string;
  updated_at?: string;
  metadata?: Record<string, unknown>;
  messages?: ConversationMessage[];
}

export interface ChatResponse {
  // Chat response text (normalized).
  // Some backends return this as `message`, others as `response`.
  message: string;
  // Optional tool attachments generated by Edge Functions (provider search, address search, etc.).
  attachments?: unknown[];
  // Legacy/optional fields (kept for compatibility with older backends).
  response?: string;
  conversation_id?: string;
  message_id?: string;
  tool_calls?: ToolCall[];
}

export interface ToolCall {
  name: string;
  args: Record<string, unknown>;
  result?: unknown;
}

export interface ChatStreamEvent {
  event: 'tool_start' | 'tool_end' | 'token' | 'message' | 'done' | 'error';
  tool?: string;
  content?: string;
  message?: string;
  attachments?: unknown[];
}

export interface DirectionsRequest {
  origin: string;
  destination: string;
  mode?: 'driving' | 'transit' | 'walking' | 'bicycling';
}

export interface DirectionsResponse {
  success: boolean;
  distance?: { text: string; value: number };
  duration?: { text: string; value: number };
  start_address?: string;
  end_address?: string;
  steps?: DirectionStep[];
  polyline?: string;
  error?: string;
}

export interface DirectionStep {
  instruction: string;
  distance: { text: string; value: number };
  duration: { text: string; value: number };
  travel_mode?: string;
  transit_details?: unknown;
}

export interface TripRecordPair {
  trip_id: number;
  pickup_sequence: number;
  drop_sequence: number;
  pick_time: string;
  drop_time: string;
  pickup_address: string;
  pickup_city: string;
  drop_address: string;
  drop_city: string;
  passengers_on_board: number;
  trip_id_return?: number;
  return_pick_time?: string;
  duration_minutes: number;
  return_gap_minutes?: number;
  route_polyline?: string;
  route_distance_meters?: number;
  route_duration_seconds?: number;
  route_summary?: string;
}

export interface TripRecordStats {
  total_records: number;
  with_return_count: number;
  pct_with_return: number;
  avg_duration_minutes: number;
  median_duration_minutes: number;
  p90_duration_minutes: number;
  avg_return_gap_minutes: number;
  earliest_pick_time: string;
  latest_drop_time: string;
  top_pickup_hotspots: { label: string; city: string; count: number }[];
  top_drop_hotspots: { label: string; city: string; count: number }[];
  busiest_pick_hours: { hour: number; count: number }[];
}

export interface HealthCheckResponse {
  status: string;
  ok?: boolean;
}

export interface TranscriptionResponse {
  text: string;
  model?: string;
  language?: string;
  duration_seconds?: number;
}

// =============================================================================
// API Configuration Check
// =============================================================================

/**
 * Check if API is configured and ready
 */
export function isApiConfigured(): boolean {
  return isSupabaseConfigured();
}

// =============================================================================
// Provider API Functions
// =============================================================================

/**
 * Geocode an address to coordinates
 *
 * @param address - Address string to geocode
 * @returns Geocode result with coordinates
 */
export async function geocodeAddress(address: string): Promise<GeocodeResult> {
  const { data, error } = await fetchEdgeFunction<GeocodeResult>('geocode', {
    params: { address },
  });

  if (error) {
    return { success: false, message: error.message };
  }

  if (!data) {
    return { success: false, message: 'No data returned' };
  }

  // Normalize coordinates format
  return {
    ...data,
    coordinates: data.coordinates || (data.lat && data.lng ? {
      latitude: data.lat,
      longitude: data.lng,
    } : undefined),
  };
}

/**
 * Get all providers
 *
 * @returns List of all providers
 */
export async function getAllProviders(): Promise<{ data: Provider[] | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<{ data: Provider[] }>('providers');
  const providers = Array.isArray(data?.data) ? data!.data.map(normalizeProviderForUi) : null;
  return { data: providers, error };
}

/**
 * Search providers by query
 *
 * @param query - Search query string
 * @returns Matching providers
 */
export async function searchProviders(
  query: string
): Promise<{ data: Provider[] | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<Provider[]>('providers/search', {
    params: { q: query },
  });
  const providers = Array.isArray(data) ? data.map(normalizeProviderForUi) : null;
  return { data: providers, error };
}

/**
 * Filter providers based on origin/destination and criteria
 *
 * @param request - Filter parameters
 * @returns Filtered providers list
 */
export async function filterProviders(
  request: ProviderFilterRequest
): Promise<{ data: ProviderFilterResponse | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<ProviderFilterResponse>('providers/filter', {
    method: 'POST',
    body: request,
  });
  if (!data) return { data: null, error };
  if (typeof data.error === 'string' && data.error.trim()) {
    return { data: null, error: new Error(data.error) };
  }
  if (
    typeof data.message === 'string' &&
    /spatial filtering unavailable|spatial provider filtering is not configured/i.test(data.message)
  ) {
    return { data: null, error: new Error(data.message) };
  }
  return {
    data: {
      ...data,
      data: Array.isArray(data.data) ? data.data.map(normalizeProviderForUi) : [],
    },
    error,
  };
}

/**
 * Get provider service zone by ID
 *
 * @param providerId - Provider ID
 * @returns Service zone GeoJSON data
 */
export async function getProviderServiceZone(
  providerId: string | number
): Promise<{ data: unknown | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction(`providers/${providerId}/service-zone`);
  return { data, error };
}

/**
 * Get a single provider by ID
 *
 * @param providerId - Provider ID
 * @returns Provider data
 */
export async function getProvider(
  providerId: string | number
): Promise<{ data: Provider | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<Provider>(`providers/${providerId}`);
  return { data: data ? normalizeProviderForUi(data) : null, error };
}

/**
 * Update a provider profile by provider_id.
 *
 * @param providerId - Provider ID
 * @param update - Editable provider fields
 * @returns Updated provider data
 */
export async function updateProvider(
  providerId: string | number,
  update: ProviderUpdate
): Promise<{ data: Provider | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<Provider>(`providers/${providerId}`, {
    method: 'PUT',
    body: update,
  });
  return { data: data ? normalizeProviderForUi(data) : null, error };
}

// =============================================================================
// Geocode API Functions
// =============================================================================

/**
 * Geocode an address using the dedicated geocode edge function
 * (Alternative to providers/geocode endpoint)
 *
 * @param address - Address to geocode
 * @returns Geocode result
 */
export async function geocode(address: string): Promise<GeocodeResult> {
  return geocodeAddress(address);
}

// =============================================================================
// Directions API Functions
// =============================================================================

/**
 * Get directions between two locations
 *
 * @param request - Directions request with origin, destination, and mode
 * @returns Directions response with route information
 */
export async function getDirections(
  request: DirectionsRequest
): Promise<{ data: DirectionsResponse | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<DirectionsResponse>('directions', {
    method: 'POST',
    body: request,
  });
  return { data, error };
}

// =============================================================================
// Chat API Functions
// =============================================================================

/**
 * Check chat server health
 *
 * @returns True if server is online
 */
export async function checkChatHealth(): Promise<boolean> {
  try {
    const { error } = await fetchEdgeFunction<HealthCheckResponse>('health');
    return error === null;
  } catch {
    return false;
  }
}

/**
 * Create a new conversation
 *
 * @param title - Optional conversation title
 * @returns New conversation data
 */
export async function createConversation(
  title: string = 'New Chat'
): Promise<{ data: Conversation | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<Conversation>('conversations', {
    method: 'POST',
    body: { title },
  });
  return { data, error };
}

/**
 * Get a conversation by ID with messages
 *
 * @param conversationId - Conversation ID
 * @returns Conversation with messages
 */
export async function getConversation(
  conversationId: string
): Promise<{ data: Conversation | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<Conversation>(`conversations/${conversationId}`);
  return { data, error };
}

/**
 * List all conversations
 *
 * @returns List of conversations
 */
export async function listConversations(): Promise<{ data: Conversation[] | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<Conversation[]>('conversations');
  return { data, error };
}

/**
 * Delete a conversation
 *
 * @param conversationId - Conversation ID to delete
 * @returns Success status
 */
export async function deleteConversation(
  conversationId: string
): Promise<{ error: Error | null }> {
  const { error } = await fetchEdgeFunction(`conversations/${conversationId}`, {
    method: 'DELETE',
  });
  return { error };
}

/**
 * Send a chat message and get response (non-streaming)
 *
 * @param conversationId - Conversation ID
 * @param message - Message content
 * @returns Chat response
 */
export async function sendChatMessage(
  conversationId: string,
  message: string,
  options: { signal?: AbortSignal; timeoutMs?: number } = {},
): Promise<{ data: ChatResponse | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<ChatResponse>('chat', {
    method: 'POST',
    body: {
      conversation_id: conversationId,
      message,
    },
    timeoutMs: options.timeoutMs ?? 45000,
    useApiFunctionsHost: true,
    signal: options.signal,
  });

  if (!data || error) return { data, error };

  // Normalize response shape across backends.
  const normalized: ChatResponse = {
    ...data,
    message: (data as unknown as { message?: string }).message ?? data.response ?? '',
  };

  return { data: normalized, error: null };
}

/**
 * Transcribe recorded voice input through a server-side OpenAI proxy.
 *
 * The browser sends only the audio blob. OpenAI credentials stay in the
 * Supabase/AWS function environment.
 */
export async function transcribeAudio(
  audioBlob: Blob,
  filename = 'voice-input.webm'
): Promise<{ data: TranscriptionResponse | null; error: Error | null }> {
  try {
    const formData = new FormData();
    formData.append('file', audioBlob, filename);

    const headers = getAuthHeaders();
    delete headers['Content-Type'];

    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), 45000);

    const response = await fetch(getEdgeFunctionUrl('transcribe'), {
      method: 'POST',
      headers,
      body: formData,
      signal: controller.signal,
    });

    window.clearTimeout(timeoutId);

    const raw = await response.text();
    let parsed: unknown = null;
    if (raw.trim()) {
      try {
        parsed = JSON.parse(raw);
      } catch {
        parsed = raw;
      }
    }

    if (!response.ok) {
      const message =
        parsed && typeof parsed === 'object' && 'error' in parsed
          ? String((parsed as { error?: unknown }).error)
          : raw || `Transcription failed: HTTP ${response.status}`;
      return { data: null, error: new Error(message) };
    }

    if (!parsed || typeof parsed !== 'object' || !('text' in parsed)) {
      return { data: null, error: new Error('Transcription response did not include text.') };
    }

    return { data: parsed as TranscriptionResponse, error: null };
  } catch (err) {
    const message = err instanceof Error && err.name === 'AbortError'
      ? 'Transcription timed out. Please try a shorter recording.'
      : err instanceof Error
        ? err.message
        : String(err);
    return { data: null, error: new Error(message) };
  }
}

/**
 * Stream chat response (SSE)
 *
 * @param conversationId - Conversation ID
 * @param newMessage - New message to send
 * @returns Async generator of chat events
 */
export async function* streamChatResponse(
  conversationId: string,
  newMessage: ConversationMessage
): AsyncGenerator<ChatStreamEvent, void, unknown> {
  const url = getEdgeFunctionUrl('chat');
  const headers = getAuthHeaders();

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      conversation_id: conversationId,
      message: newMessage.content,
      stream: true,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => '');
    throw new Error(errorText || `Chat error: ${response.status} ${response.statusText}`);
  }

  const contentType = response.headers.get('content-type') || '';

  // Some deployments return a non-streaming JSON response even when `stream: true` is sent.
  // In that case, synthesize a minimal event sequence compatible with the UI.
  if (!contentType.includes('text/event-stream')) {
    const raw = await response.text();
    if (!raw.trim()) {
      yield { event: 'done' };
      return;
    }

    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch (e) {
      throw new Error(`Chat response was not SSE or JSON: ${raw.slice(0, 200)}`);
    }

    const obj = parsed as Record<string, unknown>;
    const messageText =
      (typeof obj.message === 'string' && obj.message) ||
      (typeof obj.response === 'string' && obj.response) ||
      '';

    const attachments = Array.isArray(obj.attachments) ? obj.attachments : [];

    if (messageText) {
      yield { event: 'message', content: messageText };
    }

    yield { event: 'done', attachments };
    return;
  }

  const reader = response.body?.getReader();
  if (!reader) {
    throw new Error('No response body');
  }

  const decoder = new TextDecoder();
  let buffer = '';

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\n');
      buffer = lines.pop() || '';

      for (const line of lines) {
        if (line.startsWith('data: ')) {
          try {
            const event = JSON.parse(line.slice(6)) as ChatStreamEvent;
            yield event;
            if (event.event === 'done') {
              await reader.cancel().catch(() => undefined);
              return;
            }
          } catch (e) {
            console.warn('Failed to parse SSE event:', line, e);
          }
        }
      }
    }
  } finally {
    reader.releaseLock();
  }
}

// =============================================================================
// Messages API Functions
// =============================================================================

/**
 * Get messages for a conversation
 *
 * @param conversationId - Conversation ID
 * @returns List of messages
 */
export async function getMessages(
  conversationId: string
): Promise<{ data: ConversationMessage[] | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<ConversationMessage[]>(
    `messages?conversation_id=${conversationId}`
  );
  return { data, error };
}

/**
 * Create a message in a conversation
 *
 * @param conversationId - Conversation ID
 * @param role - Message role (user, assistant, system)
 * @param content - Message content
 * @returns Created message
 */
export async function createMessage(
  conversationId: string,
  role: string,
  content: string
): Promise<{ data: ConversationMessage | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<ConversationMessage>('messages', {
    method: 'POST',
    body: {
      conversation_id: conversationId,
      role,
      content,
    },
  });
  return { data, error };
}

// =============================================================================
// Trip Records API Functions
// =============================================================================

/**
 * Get trip record pairs
 *
 * @returns List of trip record pairs
 */
export async function getTripRecordPairs(
  options: { providerId?: string | number; mock?: boolean } = {}
): Promise<{ data: TripRecordPair[] | null; error: Error | null }> {
  const params: Record<string, string> = {};
  if (options.providerId !== undefined && options.providerId !== null) {
    params.provider_id = String(options.providerId);
  }
  if (options.mock) {
    params.mock = 'true';
  }

  const { data, error } = await fetchEdgeFunction<TripRecordPair[]>('trip-records/pairs', {
    params,
  });
  return { data, error };
}

/**
 * Get grouped trip record pairs (outbound/return structure)
 *
 * @returns Grouped trip pairs
 */
export async function getTripRecordPairsGrouped(
  options: { providerId?: string | number; mock?: boolean } = {}
): Promise<{ data: unknown[] | null; error: Error | null }> {
  const params: Record<string, string> = {};
  if (options.providerId !== undefined && options.providerId !== null) {
    params.provider_id = String(options.providerId);
  }
  if (options.mock) {
    params.mock = 'true';
  }

  const { data, error } = await fetchEdgeFunction<unknown[]>('trip-records/pairs-grouped', {
    params,
  });
  return { data, error };
}

/**
 * Get trip record statistics
 *
 * @returns Trip record statistics
 */
export async function getTripRecordStats(
  options: { providerId?: string | number; mock?: boolean } = {}
): Promise<{ data: TripRecordStats | null; error: Error | null }> {
  const params: Record<string, string> = {};
  if (options.providerId !== undefined && options.providerId !== null) {
    params.provider_id = String(options.providerId);
  }
  if (options.mock) {
    params.mock = 'true';
  }

  const { data, error } = await fetchEdgeFunction<TripRecordStats>('trip-records/stats', {
    params,
  });
  return { data, error };
}

export interface TripRecordUploadResponse {
  inserted_count: number;
  skipped_count?: number;
}

export async function uploadTripRecords(payload: {
  records: string;
  providerId?: string | number;
  filename?: string;
}): Promise<{ data: TripRecordUploadResponse | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<TripRecordUploadResponse>('trip-records/upload', {
    method: 'POST',
    body: {
      records: payload.records,
      provider_id: payload.providerId,
      filename: payload.filename,
    },
  });
  return { data, error };
}

// =============================================================================
// Replay & Examples API Functions
// =============================================================================

export interface ChatExample {
  id: string;
  conversation_id: string;
  title?: string;
  description?: string;
  category?: string;
  tags?: string[];
  is_active?: boolean;
  created_at?: string;
}

/**
 * List chat examples
 *
 * @returns List of chat examples
 */
export async function listChatExamples(): Promise<{ data: ChatExample[] | null; error: Error | null }> {
  // The Edge Function returns `{ data: ChatExample[], pagination: ... }`.
  const { data, error } = await fetchEdgeFunction<{ data: ChatExample[] }>('chat-examples');
  if (error) return { data: null, error };
  return { data: data?.data ?? null, error: null };
}

/**
 * Delete a chat example
 *
 * @param exampleId - Example ID to delete
 * @returns Success status
 */
export async function deleteChatExample(
  exampleId: string
): Promise<{ error: Error | null }> {
  const { error } = await fetchEdgeFunction(`chat-examples/${exampleId}`, {
    method: 'DELETE',
  });
  return { error };
}

/**
 * Save conversation as example
 *
 * @param conversationId - Conversation ID
 * @param options - Example metadata
 * @returns Saved example data
 */
export async function saveConversationAsExample(
  conversationId: string,
  options: {
    title?: string;
    description?: string;
    category?: string;
    tags?: string[];
  }
): Promise<{ data: unknown | null; error: Error | null }> {
  // Prefer the replay endpoint which also generates/stores replay states.
  const primary = await fetchEdgeFunction('replay/save-as-example', {
    method: 'POST',
    body: {
      conversation_id: conversationId,
      title: options.title,
      description: options.description,
      category: options.category,
      tags: options.tags,
    },
  });

  if (!primary.error) {
    return { data: primary.data, error: null };
  }

  // Fallback to legacy endpoint (creates the example record only).
  const fallback = await fetchEdgeFunction('chat-examples', {
    method: 'POST',
    body: {
      conversation_id: conversationId,
      ...options,
    },
  });

  return { data: fallback.data, error: fallback.error };
}

/**
 * Submit tester feedback on a conversation.
 *
 * The transcript travels with the submission so the stored copy is what the tester saw, not what
 * the conversation looks like after they keep chatting.
 *
 * @param feedback - Name, comment, and the conversation it refers to
 * @returns The stored feedback identifier
 */
export async function submitChatFeedback(feedback: {
  conversationId?: string | null;
  messageId?: string | null;
  name?: string;
  comment: string;
  rating?: 'up' | 'down';
  transcript?: Array<{ role: string; content: string; created_at?: string }>;
  context?: Record<string, unknown>;
}): Promise<{ data: { id: string; created_at: string } | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<{ id: string; created_at: string }>('feedback', {
    method: 'POST',
    body: {
      conversation_id: feedback.conversationId ?? null,
      message_id: feedback.messageId ?? null,
      name: feedback.name ?? null,
      comment: feedback.comment,
      rating: feedback.rating ?? 'down',
      transcript: feedback.transcript ?? [],
      context: {
        page_url: typeof window !== 'undefined' ? window.location.href : undefined,
        ...(feedback.context ?? {}),
      },
    },
  });

  return { data, error };
}

/**
 * Load example replay data
 *
 * @param conversationId - Conversation ID
 * @returns Replay data with states and config
 */
export async function loadExampleReplayData(
  conversationId: string
): Promise<{ data: unknown | null; error: Error | null }> {
  // Replay function expects `conversation_id` as a query parameter.
  const { data, error } = await fetchEdgeFunction('replay', {
    params: { conversation_id: conversationId },
  });
  return { data, error };
}

/**
 * Get conversation messages (for legacy fallback)
 *
 * @param conversationId - Conversation ID
 * @returns Messages data
 */
export async function getConversationMessages(
  conversationId: string
): Promise<{ data: { messages: ConversationMessage[] } | null; error: Error | null }> {
  try {
    if (getApiBackend() === 'aws') {
      const result = await fetchEdgeFunction<{ data: ConversationMessage[] }>('messages', {
        params: { conversation_id: conversationId, limit: '500' },
        timeoutMs: 5000,
      });
      return result.error
        ? { data: null, error: result.error }
        : { data: { messages: result.data?.data || [] }, error: null };
    }
    const params = new URLSearchParams({
      conversation_id: `eq.${conversationId}`,
      select: 'id,conversation_id,role,content,attachments,created_at',
      order: 'created_at.asc',
    });
    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), 5000);
    const response = await fetch(getSupabaseRestUrl(`messages?${params.toString()}`), {
      headers: getRestHeaders(),
      signal: controller.signal,
    });
    window.clearTimeout(timeoutId);

    if (!response.ok) {
      const message = await response.text().catch(() => '');
      return { data: null, error: new Error(message || `Messages error: ${response.status}`) };
    }

    const messages = await response.json() as ConversationMessage[];
    return { data: { messages }, error: null };
  } catch (err) {
    return { data: null, error: err instanceof Error ? err : new Error(String(err)) };
  }
}

/**
 * Get conversation tool calls (for legacy fallback)
 *
 * @param conversationId - Conversation ID
 * @returns Tool calls data
 */
export async function getConversationToolCalls(
  conversationId: string
): Promise<{ data: { tool_calls: Record<string, unknown> } | null; error: Error | null }> {
  const { data, error } = await fetchEdgeFunction<{ tool_calls: Record<string, unknown> }>('tool-calls', {
    params: { conversation_id: conversationId },
  });
  return { data, error };
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Get API mode information for debugging
 */
export function getApiModeInfo(): {
  mode: 'aws' | 'supabase';
  supabaseConfigured: boolean;
} {
  return {
    mode: getApiBackend(),
    supabaseConfigured: isSupabaseConfigured(),
  };
}

/**
 * Re-export Supabase utilities for components that need direct access
 */
export { getEdgeFunctionUrl, getAuthHeaders, isSupabaseConfigured };
